In [1]:
import pandas as pd
import numpy as np

# excel 데이터 불러오기,
tmp = pd.read_excel('data/국가산업단지_산업동향_18_01.xlsx',sheet_name=9, skiprows=2)
tmp

,산업단지,구분,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
0,서울,국가,500,6039,2534,2851,96,86,4507,23225,833,1136,108155,149962
1,녹산,국가,823,3251,708,2325,275,2527,15161,5857,3109,254,422,34712
2,대구,국가,0,0,0,0,0,0,366,107,924,0,0,1397
3,남동,국가,1834,570,2977,19515,465,4512,47748,17610,5400,3978,395,105004
4,부평,국가,411,1577,332,650,10,230,2860,5982,214,237,1316,13819
5,주안,국가,13,604,212,955,0,396,3792,7877,1699,347,129,16024
6,광주첨단,국가,0,0,0,171,21,6,3103,14297,483,0,769,18850
7,빛그린,국가,0,0,0,0,0,0,0,0,0,0,0,0
8,온산,국가,12,0,1017,5264,183,3690,1653,262,2389,12,554,15036
9,울산ㆍ미포,국가,342,96,69,14876,447,1011,5353,5702,63657,86,3572,95211
10,반월,국가,2234,8037,2907,20169,407,3572,31585,42826,12288,518,1399,125942
11,시화,국가,3422,2246,5672,12798,758,7910,54745,28362,10433,1340,2203,129889
12,시화MTV,국가,0,0,0,119,25,816,817,2260,0,0,101,4138
13,파주출판,국가,0,0,2024,0,0,0,0,0,0,0,3352,5376
14,파주탄현,국가,12,0,0,163,0,0,184,41,0,0,0,400
15,북평,국가,52,0,29,0,14,0,180,0,0,1,243,519
16,오송생명과학,국가,585,0,0,1875,0,0,0,1026,0,0,149,3635
17,석문,국가,0,0,0,52,29,39,211,0,394,0,0,725
18,아산,국가,231,0,272,1946,344,3058,2673,4101,3498,0,1080,17203
19,장항생태,국가,0,0,0,0,0,0,0,0,0,0,0,0
20,국가식품클러스터,국가,59,0,0,0,0,0,0,0,0,0,56,115
21,국가식품클러스터(외),국가,0,0,0,0,0,0,0,0,0,0,0,0
22,군산,국가,8,30,41,547,71,148,771,134,4096,0,143,5989
23,군산2,국가,217,8,347,643,152,587,1515,414,1335,12,88,5318
24,익산,국가,339,510,53,660,53,0,92,1144,381,224,0,3456
25,광양,국가,0,54,5,375,610,7192,600,288,638,13,616,10391
26,대불,국가,124,0,83,374,338,106,725,32,1749,22,36,3589
27,대불(외국인),국가,6,0,0,0,0,0,163,0,995,0,0,1164
28,여수,국가,7,0,25,19282,273,95,2206,231,0,61,418,22598
29,구미,국가,577,3256,798,5301,2936,736,22045,53299,976,50,1412,91386
30,구미(외),국가,0,0,0,993,8,0,231,2254,308,0,0,3794
31,포항,국가,0,0,0,765,791,8455,139,394,331,174,415,11464
32,포항블루밸리,국가,0,0,0,0,0,0,0,0,0,0,0,0
33,안정,국가,x,x,x,x,x,x,x,x,x,x,x,x
34,진해,국가,x,x,x,x,x,x,x,x,x,x,x,x
35,창원,국가,784,0,257,994,42,3835,74766,23659,20634,259,1042,126272
36,계,NaN,12592,26278,20362,113663,8348,49007,278655,241384,139870,8724,128065,1026948

In [2]:
# 다 국가 산업단지이기 때문에 "구분" 칼럼 삭제하기
tmp.drop(["구분"], axis=1, inplace=True)
tmp

,산업단지,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
0,서울,500,6039,2534,2851,96,86,4507,23225,833,1136,108155,149962
1,녹산,823,3251,708,2325,275,2527,15161,5857,3109,254,422,34712
2,대구,0,0,0,0,0,0,366,107,924,0,0,1397
3,남동,1834,570,2977,19515,465,4512,47748,17610,5400,3978,395,105004
4,부평,411,1577,332,650,10,230,2860,5982,214,237,1316,13819
5,주안,13,604,212,955,0,396,3792,7877,1699,347,129,16024
6,광주첨단,0,0,0,171,21,6,3103,14297,483,0,769,18850
7,빛그린,0,0,0,0,0,0,0,0,0,0,0,0
8,온산,12,0,1017,5264,183,3690,1653,262,2389,12,554,15036
9,울산ㆍ미포,342,96,69,14876,447,1011,5353,5702,63657,86,3572,95211
10,반월,2234,8037,2907,20169,407,3572,31585,42826,12288,518,1399,125942
11,시화,3422,2246,5672,12798,758,7910,54745,28362,10433,1340,2203,129889
12,시화MTV,0,0,0,119,25,816,817,2260,0,0,101,4138
13,파주출판,0,0,2024,0,0,0,0,0,0,0,3352,5376
14,파주탄현,12,0,0,163,0,0,184,41,0,0,0,400
15,북평,52,0,29,0,14,0,180,0,0,1,243,519
16,오송생명과학,585,0,0,1875,0,0,0,1026,0,0,149,3635
17,석문,0,0,0,52,29,39,211,0,394,0,0,725
18,아산,231,0,272,1946,344,3058,2673,4101,3498,0,1080,17203
19,장항생태,0,0,0,0,0,0,0,0,0,0,0,0
20,국가식품클러스터,59,0,0,0,0,0,0,0,0,0,56,115
21,국가식품클러스터(외),0,0,0,0,0,0,0,0,0,0,0,0
22,군산,8,30,41,547,71,148,771,134,4096,0,143,5989
23,군산2,217,8,347,643,152,587,1515,414,1335,12,88,5318
24,익산,339,510,53,660,53,0,92,1144,381,224,0,3456
25,광양,0,54,5,375,610,7192,600,288,638,13,616,10391
26,대불,124,0,83,374,338,106,725,32,1749,22,36,3589
27,대불(외국인),6,0,0,0,0,0,163,0,995,0,0,1164
28,여수,7,0,25,19282,273,95,2206,231,0,61,418,22598
29,구미,577,3256,798,5301,2936,736,22045,53299,976,50,1412,91386
30,구미(외),0,0,0,993,8,0,231,2254,308,0,0,3794
31,포항,0,0,0,765,791,8455,139,394,331,174,415,11464
32,포항블루밸리,0,0,0,0,0,0,0,0,0,0,0,0
33,안정,x,x,x,x,x,x,x,x,x,x,x,x
34,진해,x,x,x,x,x,x,x,x,x,x,x,x
35,창원,784,0,257,994,42,3835,74766,23659,20634,259,1042,126272
36,계,12592,26278,20362,113663,8348,49007,278655,241384,139870,8724,128065,1026948

In [3]:
# 산업단지 명을 인덱스로 사용하기
tmp.set_index("산업단지", inplace=True)
tmp

,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
산업단지,,,,,,,,,,,,
서울,500,6039,2534,2851,96,86,4507,23225,833,1136,108155,149962
녹산,823,3251,708,2325,275,2527,15161,5857,3109,254,422,34712
대구,0,0,0,0,0,0,366,107,924,0,0,1397
남동,1834,570,2977,19515,465,4512,47748,17610,5400,3978,395,105004
부평,411,1577,332,650,10,230,2860,5982,214,237,1316,13819
주안,13,604,212,955,0,396,3792,7877,1699,347,129,16024
광주첨단,0,0,0,171,21,6,3103,14297,483,0,769,18850
빛그린,0,0,0,0,0,0,0,0,0,0,0,0
온산,12,0,1017,5264,183,3690,1653,262,2389,12,554,15036
울산ㆍ미포,342,96,69,14876,447,1011,5353,5702,63657,86,3572,95211
반월,2234,8037,2907,20169,407,3572,31585,42826,12288,518,1399,125942
시화,3422,2246,5672,12798,758,7910,54745,28362,10433,1340,2203,129889
시화MTV,0,0,0,119,25,816,817,2260,0,0,101,4138
파주출판,0,0,2024,0,0,0,0,0,0,0,3352,5376
파주탄현,12,0,0,163,0,0,184,41,0,0,0,400
북평,52,0,29,0,14,0,180,0,0,1,243,519
오송생명과학,585,0,0,1875,0,0,0,1026,0,0,149,3635
석문,0,0,0,52,29,39,211,0,394,0,0,725
아산,231,0,272,1946,344,3058,2673,4101,3498,0,1080,17203
장항생태,0,0,0,0,0,0,0,0,0,0,0,0
국가식품클러스터,59,0,0,0,0,0,0,0,0,0,56,115
국가식품클러스터(외),0,0,0,0,0,0,0,0,0,0,0,0
군산,8,30,41,547,71,148,771,134,4096,0,143,5989
군산2,217,8,347,643,152,587,1515,414,1335,12,88,5318
익산,339,510,53,660,53,0,92,1144,381,224,0,3456
광양,0,54,5,375,610,7192,600,288,638,13,616,10391
대불,124,0,83,374,338,106,725,32,1749,22,36,3589
대불(외국인),6,0,0,0,0,0,163,0,995,0,0,1164
여수,7,0,25,19282,273,95,2206,231,0,61,418,22598
구미,577,3256,798,5301,2936,736,22045,53299,976,50,1412,91386
구미(외),0,0,0,993,8,0,231,2254,308,0,0,3794
포항,0,0,0,765,791,8455,139,394,331,174,415,11464
포항블루밸리,0,0,0,0,0,0,0,0,0,0,0,0
안정,x,x,x,x,x,x,x,x,x,x,x,x
진해,x,x,x,x,x,x,x,x,x,x,x,x
창원,784,0,257,994,42,3835,74766,23659,20634,259,1042,126272
계,12592,26278,20362,113663,8348,49007,278655,241384,139870,8724,128065,1026948

In [4]:
# 계가 0인 산업단지 없애기
tmp = tmp[tmp.계 != 0]
tmp

,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
산업단지,,,,,,,,,,,,
서울,500,6039,2534,2851,96,86,4507,23225,833,1136,108155,149962
녹산,823,3251,708,2325,275,2527,15161,5857,3109,254,422,34712
대구,0,0,0,0,0,0,366,107,924,0,0,1397
남동,1834,570,2977,19515,465,4512,47748,17610,5400,3978,395,105004
부평,411,1577,332,650,10,230,2860,5982,214,237,1316,13819
주안,13,604,212,955,0,396,3792,7877,1699,347,129,16024
광주첨단,0,0,0,171,21,6,3103,14297,483,0,769,18850
온산,12,0,1017,5264,183,3690,1653,262,2389,12,554,15036
울산ㆍ미포,342,96,69,14876,447,1011,5353,5702,63657,86,3572,95211
반월,2234,8037,2907,20169,407,3572,31585,42826,12288,518,1399,125942
시화,3422,2246,5672,12798,758,7910,54745,28362,10433,1340,2203,129889
시화MTV,0,0,0,119,25,816,817,2260,0,0,101,4138
파주출판,0,0,2024,0,0,0,0,0,0,0,3352,5376
파주탄현,12,0,0,163,0,0,184,41,0,0,0,400
북평,52,0,29,0,14,0,180,0,0,1,243,519
오송생명과학,585,0,0,1875,0,0,0,1026,0,0,149,3635
석문,0,0,0,52,29,39,211,0,394,0,0,725
아산,231,0,272,1946,344,3058,2673,4101,3498,0,1080,17203
국가식품클러스터,59,0,0,0,0,0,0,0,0,0,56,115
군산,8,30,41,547,71,148,771,134,4096,0,143,5989
군산2,217,8,347,643,152,587,1515,414,1335,12,88,5318
익산,339,510,53,660,53,0,92,1144,381,224,0,3456
광양,0,54,5,375,610,7192,600,288,638,13,616,10391
대불,124,0,83,374,338,106,725,32,1749,22,36,3589
대불(외국인),6,0,0,0,0,0,163,0,995,0,0,1164
여수,7,0,25,19282,273,95,2206,231,0,61,418,22598
구미,577,3256,798,5301,2936,736,22045,53299,976,50,1412,91386
구미(외),0,0,0,993,8,0,231,2254,308,0,0,3794
포항,0,0,0,765,791,8455,139,394,331,174,415,11464
안정,x,x,x,x,x,x,x,x,x,x,x,x
진해,x,x,x,x,x,x,x,x,x,x,x,x
창원,784,0,257,994,42,3835,74766,23659,20634,259,1042,126272
계,12592,26278,20362,113663,8348,49007,278655,241384,139870,8724,128065,1026948

In [5]:
# 'x' 값을 가지는 행 삭제하기
tmp = tmp.replace('x', np.nan).dropna()
tmp

,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
산업단지,,,,,,,,,,,,
서울,500.0,6039.0,2534.0,2851.0,96.0,86.0,4507.0,23225.0,833.0,1136.0,108155.0,149962.0
녹산,823.0,3251.0,708.0,2325.0,275.0,2527.0,15161.0,5857.0,3109.0,254.0,422.0,34712.0
대구,0.0,0.0,0.0,0.0,0.0,0.0,366.0,107.0,924.0,0.0,0.0,1397.0
남동,1834.0,570.0,2977.0,19515.0,465.0,4512.0,47748.0,17610.0,5400.0,3978.0,395.0,105004.0
부평,411.0,1577.0,332.0,650.0,10.0,230.0,2860.0,5982.0,214.0,237.0,1316.0,13819.0
주안,13.0,604.0,212.0,955.0,0.0,396.0,3792.0,7877.0,1699.0,347.0,129.0,16024.0
광주첨단,0.0,0.0,0.0,171.0,21.0,6.0,3103.0,14297.0,483.0,0.0,769.0,18850.0
온산,12.0,0.0,1017.0,5264.0,183.0,3690.0,1653.0,262.0,2389.0,12.0,554.0,15036.0
울산ㆍ미포,342.0,96.0,69.0,14876.0,447.0,1011.0,5353.0,5702.0,63657.0,86.0,3572.0,95211.0
반월,2234.0,8037.0,2907.0,20169.0,407.0,3572.0,31585.0,42826.0,12288.0,518.0,1399.0,125942.0
시화,3422.0,2246.0,5672.0,12798.0,758.0,7910.0,54745.0,28362.0,10433.0,1340.0,2203.0,129889.0
시화MTV,0.0,0.0,0.0,119.0,25.0,816.0,817.0,2260.0,0.0,0.0,101.0,4138.0
파주출판,0.0,0.0,2024.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3352.0,5376.0
파주탄현,12.0,0.0,0.0,163.0,0.0,0.0,184.0,41.0,0.0,0.0,0.0,400.0
북평,52.0,0.0,29.0,0.0,14.0,0.0,180.0,0.0,0.0,1.0,243.0,519.0
오송생명과학,585.0,0.0,0.0,1875.0,0.0,0.0,0.0,1026.0,0.0,0.0,149.0,3635.0
석문,0.0,0.0,0.0,52.0,29.0,39.0,211.0,0.0,394.0,0.0,0.0,725.0
아산,231.0,0.0,272.0,1946.0,344.0,3058.0,2673.0,4101.0,3498.0,0.0,1080.0,17203.0
국가식품클러스터,59.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,56.0,115.0
군산,8.0,30.0,41.0,547.0,71.0,148.0,771.0,134.0,4096.0,0.0,143.0,5989.0
군산2,217.0,8.0,347.0,643.0,152.0,587.0,1515.0,414.0,1335.0,12.0,88.0,5318.0
익산,339.0,510.0,53.0,660.0,53.0,0.0,92.0,1144.0,381.0,224.0,0.0,3456.0
광양,0.0,54.0,5.0,375.0,610.0,7192.0,600.0,288.0,638.0,13.0,616.0,10391.0
대불,124.0,0.0,83.0,374.0,338.0,106.0,725.0,32.0,1749.0,22.0,36.0,3589.0
대불(외국인),6.0,0.0,0.0,0.0,0.0,0.0,163.0,0.0,995.0,0.0,0.0,1164.0
여수,7.0,0.0,25.0,19282.0,273.0,95.0,2206.0,231.0,0.0,61.0,418.0,22598.0
구미,577.0,3256.0,798.0,5301.0,2936.0,736.0,22045.0,53299.0,976.0,50.0,1412.0,91386.0
구미(외),0.0,0.0,0.0,993.0,8.0,0.0,231.0,2254.0,308.0,0.0,0.0,3794.0
포항,0.0,0.0,0.0,765.0,791.0,8455.0,139.0,394.0,331.0,174.0,415.0,11464.0
창원,784.0,0.0,257.0,994.0,42.0,3835.0,74766.0,23659.0,20634.0,259.0,1042.0,126272.0
계,12592.0,26278.0,20362.0,113663.0,8348.0,49007.0,278655.0,241384.0,139870.0,8724.0,128065.0,1026948.0

In [6]:
# 계 칼럼 삭제하기
tmp_without_total = tmp.drop(["계"], axis=1)
tmp_without_total

,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조
산업단지,,,,,,,,,,,
서울,500.0,6039.0,2534.0,2851.0,96.0,86.0,4507.0,23225.0,833.0,1136.0,108155.0
녹산,823.0,3251.0,708.0,2325.0,275.0,2527.0,15161.0,5857.0,3109.0,254.0,422.0
대구,0.0,0.0,0.0,0.0,0.0,0.0,366.0,107.0,924.0,0.0,0.0
남동,1834.0,570.0,2977.0,19515.0,465.0,4512.0,47748.0,17610.0,5400.0,3978.0,395.0
부평,411.0,1577.0,332.0,650.0,10.0,230.0,2860.0,5982.0,214.0,237.0,1316.0
주안,13.0,604.0,212.0,955.0,0.0,396.0,3792.0,7877.0,1699.0,347.0,129.0
광주첨단,0.0,0.0,0.0,171.0,21.0,6.0,3103.0,14297.0,483.0,0.0,769.0
온산,12.0,0.0,1017.0,5264.0,183.0,3690.0,1653.0,262.0,2389.0,12.0,554.0
울산ㆍ미포,342.0,96.0,69.0,14876.0,447.0,1011.0,5353.0,5702.0,63657.0,86.0,3572.0
반월,2234.0,8037.0,2907.0,20169.0,407.0,3572.0,31585.0,42826.0,12288.0,518.0,1399.0
시화,3422.0,2246.0,5672.0,12798.0,758.0,7910.0,54745.0,28362.0,10433.0,1340.0,2203.0
시화MTV,0.0,0.0,0.0,119.0,25.0,816.0,817.0,2260.0,0.0,0.0,101.0
파주출판,0.0,0.0,2024.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3352.0
파주탄현,12.0,0.0,0.0,163.0,0.0,0.0,184.0,41.0,0.0,0.0,0.0
북평,52.0,0.0,29.0,0.0,14.0,0.0,180.0,0.0,0.0,1.0,243.0
오송생명과학,585.0,0.0,0.0,1875.0,0.0,0.0,0.0,1026.0,0.0,0.0,149.0
석문,0.0,0.0,0.0,52.0,29.0,39.0,211.0,0.0,394.0,0.0,0.0
아산,231.0,0.0,272.0,1946.0,344.0,3058.0,2673.0,4101.0,3498.0,0.0,1080.0
국가식품클러스터,59.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,56.0
군산,8.0,30.0,41.0,547.0,71.0,148.0,771.0,134.0,4096.0,0.0,143.0
군산2,217.0,8.0,347.0,643.0,152.0,587.0,1515.0,414.0,1335.0,12.0,88.0
익산,339.0,510.0,53.0,660.0,53.0,0.0,92.0,1144.0,381.0,224.0,0.0
광양,0.0,54.0,5.0,375.0,610.0,7192.0,600.0,288.0,638.0,13.0,616.0
대불,124.0,0.0,83.0,374.0,338.0,106.0,725.0,32.0,1749.0,22.0,36.0
대불(외국인),6.0,0.0,0.0,0.0,0.0,0.0,163.0,0.0,995.0,0.0,0.0
여수,7.0,0.0,25.0,19282.0,273.0,95.0,2206.0,231.0,0.0,61.0,418.0
구미,577.0,3256.0,798.0,5301.0,2936.0,736.0,22045.0,53299.0,976.0,50.0,1412.0
구미(외),0.0,0.0,0.0,993.0,8.0,0.0,231.0,2254.0,308.0,0.0,0.0
포항,0.0,0.0,0.0,765.0,791.0,8455.0,139.0,394.0,331.0,174.0,415.0
창원,784.0,0.0,257.0,994.0,42.0,3835.0,74766.0,23659.0,20634.0,259.0,1042.0
계,12592.0,26278.0,20362.0,113663.0,8348.0,49007.0,278655.0,241384.0,139870.0,8724.0,128065.0

In [7]:
# 각 산업단지 별 제일 고용인구가 많은 업종
most = tmp_without_total.idxmax(axis=1)
most

산업단지
서울           비제조
녹산            기계
대구          운송장비
남동            기계
부평          전기전자
주안          전기전자
광주첨단        전기전자
온산          석유화학
울산ㆍ미포       운송장비
반월          전기전자
시화            기계
시화MTV       전기전자
파주출판         비제조
파주탄현          기계
북평           비제조
오송생명과학      석유화학
석문          운송장비
아산          전기전자
국가식품클러스터     음식료
군산          운송장비
군산2           기계
익산          전기전자
광양            철강
대불          운송장비
대불(외국인)     운송장비
여수          석유화학
구미          전기전자
구미(외)       전기전자
포항            철강
창원            기계
계             기계
dtype: object

In [8]:
# 각 산업단지 별 제일 고용인구가 많은 업종의 종목명
most = tmp_without_total.max(axis=1)
most

산업단지
서울          108155.0
녹산           15161.0
대구             924.0
남동           47748.0
부평            5982.0
주안            7877.0
광주첨단         14297.0
온산            5264.0
울산ㆍ미포        63657.0
반월           42826.0
시화           54745.0
시화MTV         2260.0
파주출판          3352.0
파주탄현           184.0
북평             243.0
오송생명과학        1875.0
석문             394.0
아산            4101.0
국가식품클러스터        59.0
군산            4096.0
군산2           1515.0
익산            1144.0
광양            7192.0
대불            1749.0
대불(외국인)        995.0
여수           19282.0
구미           53299.0
구미(외)         2254.0
포항            8455.0
창원           74766.0
계           278655.0
dtype: float64

In [9]:
# 각 산업단지 별 제일 고용인구가 많은 종목의 차지비율
percentage = most / tmp_without_total.sum(axis=1) * 100
percentage

산업단지
서울          72.121604
녹산          43.676538
대구          66.141732
남동          45.472553
부평          43.288226
주안          49.157514
광주첨단        75.846154
온산          35.009311
울산ㆍ미포       66.858871
반월          34.004542
시화          42.147526
시화MTV       54.615756
파주출판        62.351190
파주탄현        46.000000
북평          46.820809
오송생명과학      51.581843
석문          54.344828
아산          23.838865
국가식품클러스터    51.304348
군산          68.392052
군산2         28.488153
익산          33.101852
광양          69.213743
대불          48.732237
대불(외국인)     85.481100
여수          85.326135
구미          58.322938
구미(외)       59.409594
포항          73.752617
창원          59.210276
계           27.134285
dtype: float64

In [10]:
# 이후 불러올 데이터들 위의 과정을 하면서 불러오기
tmp2 = pd.read_excel('data/국가산업단지_산업동향_18_02.xlsx',sheet_name=9, skiprows=2)
tmp2 = tmp2[tmp2.계 != 0.0]
tmp2 = tmp2.replace('x', np.nan).dropna()
tmp2.drop(["구분", '계'], axis=1, inplace=True) 
tmp2.set_index("산업단지", inplace=True)
tmp2

,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조
산업단지,,,,,,,,,,,
서울,495.0,6036.0,2512.0,2893.0,95.0,84.0,4507.0,23050.0,829.0,1142.0,108593.0
녹산,829.0,3247.0,710.0,2336.0,275.0,2500.0,14755.0,5964.0,3117.0,251.0,131.0
대구,0.0,0.0,0.0,0.0,0.0,0.0,368.0,106.0,920.0,0.0,0.0
남동,1836.0,551.0,2974.0,19574.0,464.0,4527.0,47159.0,17444.0,5398.0,3987.0,386.0
부평,408.0,1583.0,330.0,656.0,10.0,230.0,2911.0,5983.0,212.0,228.0,1308.0
주안,13.0,614.0,210.0,950.0,0.0,402.0,3759.0,7988.0,1710.0,347.0,122.0
광주첨단,0.0,0.0,0.0,170.0,21.0,6.0,3045.0,14665.0,477.0,0.0,773.0
온산,12.0,0.0,1016.0,5263.0,169.0,3677.0,1634.0,260.0,2304.0,12.0,563.0
울산ㆍ미포,342.0,99.0,69.0,14910.0,447.0,1011.0,5406.0,5690.0,63640.0,86.0,3624.0
반월,2251.0,7686.0,2891.0,20176.0,407.0,3551.0,31787.0,41800.0,12253.0,520.0,1387.0
시화,3422.0,2215.0,5664.0,12688.0,739.0,7856.0,54416.0,27909.0,10457.0,1341.0,2298.0
시화MTV,0.0,0.0,0.0,120.0,25.0,815.0,831.0,2247.0,0.0,0.0,101.0
파주출판,0.0,0.0,2026.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3359.0
파주탄현,12.0,0.0,0.0,163.0,0.0,0.0,182.0,41.0,0.0,0.0,0.0
북평,49.0,0.0,29.0,0.0,14.0,0.0,180.0,0.0,0.0,1.0,261.0
오송생명과학,578.0,0.0,0.0,1917.0,0.0,0.0,0.0,1032.0,0.0,0.0,158.0
석문,0.0,0.0,0.0,52.0,29.0,39.0,214.0,0.0,334.0,0.0,0.0
아산,230.0,0.0,261.0,1992.0,342.0,3052.0,2681.0,4116.0,3495.0,0.0,1091.0
국가식품클러스터,71.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.0
군산,8.0,30.0,40.0,522.0,71.0,147.0,765.0,138.0,2222.0,0.0,203.0
군산2,211.0,8.0,333.0,629.0,152.0,600.0,1532.0,484.0,1191.0,12.0,94.0
익산,330.0,499.0,53.0,662.0,53.0,0.0,92.0,1143.0,377.0,224.0,0.0
광양,0.0,60.0,5.0,373.0,588.0,7176.0,596.0,294.0,636.0,13.0,617.0
대불,123.0,0.0,83.0,374.0,337.0,106.0,709.0,31.0,1862.0,22.0,36.0
대불(외국인),6.0,0.0,0.0,0.0,0.0,0.0,164.0,0.0,1174.0,0.0,0.0
여수,6.0,0.0,25.0,19158.0,273.0,96.0,2158.0,231.0,0.0,61.0,417.0
구미,574.0,3447.0,838.0,5221.0,2993.0,737.0,22048.0,53295.0,970.0,50.0,1424.0
구미(외),0.0,0.0,0.0,984.0,8.0,0.0,261.0,2429.0,309.0,0.0,0.0
포항,0.0,0.0,0.0,775.0,791.0,8448.0,139.0,394.0,331.0,174.0,415.0
창원,715.0,0.0,249.0,1008.0,42.0,3831.0,75052.0,23835.0,20632.0,259.0,909.0

In [11]:
tmp_set = set(tmp.산업단지.values)
tmp2_set = set(tmp2.산업단지.values)
print('22년 자료에는 있고, 18년엔 없음', tmp2_set - tmp_set)
print('18년 자료에는 있고, 22년엔 없음', tmp_set - tmp2_set)

AttributeError: 'DataFrame' object has no attribute '산업단지'