# 시각화를 위한 데이터 전처리 시도
다양한 시각화를 위해 어떻게 정제하면 좋을지 만들어보기

In [8]:
import pandas as pd
import numpy as np

# excel 데이터 불러오기,
tmp = pd.read_excel('data/국가산업단지_산업동향_22_07.xlsx',sheet_name=9, skiprows=2)
tmp

,산업단지,구분,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
0,서울,국가,814,7754,3442,5880,187,109,7032,25509,855,1623,92288,145493
1,녹산,국가,995,1772,465,1384,207,2044,13078,6047,1891,164,616,28663
2,대구,국가,0,0,0,23,19,0,1397,732,2001,0,0,4172
3,남동,국가,3454,355,4022,14799,381,3393,37933,12367,4891,2672,1131,85398
4,부평,국가,374,468,540,806,5,51,2372,4873,302,193,623,10607
5,주안,국가,42,190,256,1317,41,452,2522,5301,1515,265,364,12265
6,광주첨단,국가,0,34,0,309,23,8,3300,11890,539,0,3387,19490
7,빛그린,국가,0,0,29,115,0,0,99,85,655,0,98,1081
8,온산,국가,24,8,959,5393,116,4052,952,229,1900,49,1000,14682
9,울산ㆍ미포,국가,213,69,52,15529,338,973,4101,2777,63871,16,4113,92052
10,반월,국가,2119,4439,2983,16451,353,2609,35548,35285,7872,559,1274,109492
11,시화,국가,2979,1250,3236,13924,367,6660,62149,23674,7151,1104,2019,124513
12,시화MTV,국가,0,0,0,485,36,1671,4141,7205,0,0,442,13980
13,파주탄현,국가,2,3,2,57,0,1,166,27,22,0,1,281
14,동두천,NaN,0,0,0,0,0,0,0,0,0,0,0,0
15,북평,국가,35,0,12,1,2,0,287,9,0,1,403,750
16,오송생명과학,국가,81,0,0,3841,0,0,0,1043,0,0,120,5085
17,석문,국가,0,0,0,381,46,110,306,41,560,0,2,1446
18,아산,국가,386,4,271,4402,305,3150,2371,571,2506,0,961,14927
19,장항생태,국가,264,0,0,143,0,29,15,0,10,0,0,461
20,국가식품클러스터,국가,660,0,92,3,0,0,0,0,0,0,192,947
21,국가식품클러스터(외),국가,X,X,X,X,X,X,X,X,X,X,X,X
22,군산,국가,16,8,31,468,49,225,925,172,2382,37,153,4466
23,군산2,국가,230,11,259,736,122,869,1533,46,710,12,203,4731
24,익산,국가,183,359,2,861,66,0,89,1057,336,209,45,3207
25,광양,국가,0,23,5,528,1143,8667,2876,355,128,5,637,14367
26,대불,국가,94,54,94,366,289,115,985,71,2576,10,54,4708
27,대불(외국인),국가,5,0,0,0,0,0,115,0,787,0,1,908
28,여수,국가,23,0,27,21722,419,210,1196,170,0,265,992,25024
29,구미,국가,624,2803,689,5249,4058,863,22088,41007,1368,154,631,79534
30,구미(외),국가,0,1,0,501,809,0,447,2000,237,0,0,3995
31,포항,국가,0,0,0,477,644,9268,219,437,586,19,469,12119
32,포항블루밸리,국가,X,X,X,X,X,X,X,X,X,X,X,X
33,경남항공,국가,0,0,0,0,0,0,0,0,0,0,0,0
34,밀양나노,국가,X,X,X,X,X,X,X,X,X,X,X,X
35,안정,국가,0,0,0,0,0,0,113,0,877,0,1,991
36,진해,국가,X,X,X,X,X,X,X,X,X,X,X,X
37,창원,국가,789,39,267,517,258,9471,61962,27195,15570,194,1525,117787
38,계,NaN,14431,19644,17735,116668,10292,55001,270317,210192,123240,7551,113984,959055

In [9]:
# 다 국가 산업단지이기 때문에 "구분" 칼럼 삭제하기
tmp.drop(["구분"], axis=1, inplace=True)
tmp

,산업단지,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
0,서울,814,7754,3442,5880,187,109,7032,25509,855,1623,92288,145493
1,녹산,995,1772,465,1384,207,2044,13078,6047,1891,164,616,28663
2,대구,0,0,0,23,19,0,1397,732,2001,0,0,4172
3,남동,3454,355,4022,14799,381,3393,37933,12367,4891,2672,1131,85398
4,부평,374,468,540,806,5,51,2372,4873,302,193,623,10607
5,주안,42,190,256,1317,41,452,2522,5301,1515,265,364,12265
6,광주첨단,0,34,0,309,23,8,3300,11890,539,0,3387,19490
7,빛그린,0,0,29,115,0,0,99,85,655,0,98,1081
8,온산,24,8,959,5393,116,4052,952,229,1900,49,1000,14682
9,울산ㆍ미포,213,69,52,15529,338,973,4101,2777,63871,16,4113,92052
10,반월,2119,4439,2983,16451,353,2609,35548,35285,7872,559,1274,109492
11,시화,2979,1250,3236,13924,367,6660,62149,23674,7151,1104,2019,124513
12,시화MTV,0,0,0,485,36,1671,4141,7205,0,0,442,13980
13,파주탄현,2,3,2,57,0,1,166,27,22,0,1,281
14,동두천,0,0,0,0,0,0,0,0,0,0,0,0
15,북평,35,0,12,1,2,0,287,9,0,1,403,750
16,오송생명과학,81,0,0,3841,0,0,0,1043,0,0,120,5085
17,석문,0,0,0,381,46,110,306,41,560,0,2,1446
18,아산,386,4,271,4402,305,3150,2371,571,2506,0,961,14927
19,장항생태,264,0,0,143,0,29,15,0,10,0,0,461
20,국가식품클러스터,660,0,92,3,0,0,0,0,0,0,192,947
21,국가식품클러스터(외),X,X,X,X,X,X,X,X,X,X,X,X
22,군산,16,8,31,468,49,225,925,172,2382,37,153,4466
23,군산2,230,11,259,736,122,869,1533,46,710,12,203,4731
24,익산,183,359,2,861,66,0,89,1057,336,209,45,3207
25,광양,0,23,5,528,1143,8667,2876,355,128,5,637,14367
26,대불,94,54,94,366,289,115,985,71,2576,10,54,4708
27,대불(외국인),5,0,0,0,0,0,115,0,787,0,1,908
28,여수,23,0,27,21722,419,210,1196,170,0,265,992,25024
29,구미,624,2803,689,5249,4058,863,22088,41007,1368,154,631,79534
30,구미(외),0,1,0,501,809,0,447,2000,237,0,0,3995
31,포항,0,0,0,477,644,9268,219,437,586,19,469,12119
32,포항블루밸리,X,X,X,X,X,X,X,X,X,X,X,X
33,경남항공,0,0,0,0,0,0,0,0,0,0,0,0
34,밀양나노,X,X,X,X,X,X,X,X,X,X,X,X
35,안정,0,0,0,0,0,0,113,0,877,0,1,991
36,진해,X,X,X,X,X,X,X,X,X,X,X,X
37,창원,789,39,267,517,258,9471,61962,27195,15570,194,1525,117787
38,계,14431,19644,17735,116668,10292,55001,270317,210192,123240,7551,113984,959055

In [10]:
# 산업단지 명을 인덱스로 사용하기
tmp.set_index("산업단지", inplace=True)
tmp

,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
산업단지,,,,,,,,,,,,
서울,814,7754,3442,5880,187,109,7032,25509,855,1623,92288,145493
녹산,995,1772,465,1384,207,2044,13078,6047,1891,164,616,28663
대구,0,0,0,23,19,0,1397,732,2001,0,0,4172
남동,3454,355,4022,14799,381,3393,37933,12367,4891,2672,1131,85398
부평,374,468,540,806,5,51,2372,4873,302,193,623,10607
주안,42,190,256,1317,41,452,2522,5301,1515,265,364,12265
광주첨단,0,34,0,309,23,8,3300,11890,539,0,3387,19490
빛그린,0,0,29,115,0,0,99,85,655,0,98,1081
온산,24,8,959,5393,116,4052,952,229,1900,49,1000,14682
울산ㆍ미포,213,69,52,15529,338,973,4101,2777,63871,16,4113,92052
반월,2119,4439,2983,16451,353,2609,35548,35285,7872,559,1274,109492
시화,2979,1250,3236,13924,367,6660,62149,23674,7151,1104,2019,124513
시화MTV,0,0,0,485,36,1671,4141,7205,0,0,442,13980
파주탄현,2,3,2,57,0,1,166,27,22,0,1,281
동두천,0,0,0,0,0,0,0,0,0,0,0,0
북평,35,0,12,1,2,0,287,9,0,1,403,750
오송생명과학,81,0,0,3841,0,0,0,1043,0,0,120,5085
석문,0,0,0,381,46,110,306,41,560,0,2,1446
아산,386,4,271,4402,305,3150,2371,571,2506,0,961,14927
장항생태,264,0,0,143,0,29,15,0,10,0,0,461
국가식품클러스터,660,0,92,3,0,0,0,0,0,0,192,947
국가식품클러스터(외),X,X,X,X,X,X,X,X,X,X,X,X
군산,16,8,31,468,49,225,925,172,2382,37,153,4466
군산2,230,11,259,736,122,869,1533,46,710,12,203,4731
익산,183,359,2,861,66,0,89,1057,336,209,45,3207
광양,0,23,5,528,1143,8667,2876,355,128,5,637,14367
대불,94,54,94,366,289,115,985,71,2576,10,54,4708
대불(외국인),5,0,0,0,0,0,115,0,787,0,1,908
여수,23,0,27,21722,419,210,1196,170,0,265,992,25024
구미,624,2803,689,5249,4058,863,22088,41007,1368,154,631,79534
구미(외),0,1,0,501,809,0,447,2000,237,0,0,3995
포항,0,0,0,477,644,9268,219,437,586,19,469,12119
포항블루밸리,X,X,X,X,X,X,X,X,X,X,X,X
경남항공,0,0,0,0,0,0,0,0,0,0,0,0
밀양나노,X,X,X,X,X,X,X,X,X,X,X,X
안정,0,0,0,0,0,0,113,0,877,0,1,991
진해,X,X,X,X,X,X,X,X,X,X,X,X
창원,789,39,267,517,258,9471,61962,27195,15570,194,1525,117787
계,14431,19644,17735,116668,10292,55001,270317,210192,123240,7551,113984,959055

In [11]:
# 계가 0인 산업단지 없애기
tmp = tmp[tmp.계 != 0]
tmp

,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
산업단지,,,,,,,,,,,,
서울,814,7754,3442,5880,187,109,7032,25509,855,1623,92288,145493
녹산,995,1772,465,1384,207,2044,13078,6047,1891,164,616,28663
대구,0,0,0,23,19,0,1397,732,2001,0,0,4172
남동,3454,355,4022,14799,381,3393,37933,12367,4891,2672,1131,85398
부평,374,468,540,806,5,51,2372,4873,302,193,623,10607
주안,42,190,256,1317,41,452,2522,5301,1515,265,364,12265
광주첨단,0,34,0,309,23,8,3300,11890,539,0,3387,19490
빛그린,0,0,29,115,0,0,99,85,655,0,98,1081
온산,24,8,959,5393,116,4052,952,229,1900,49,1000,14682
울산ㆍ미포,213,69,52,15529,338,973,4101,2777,63871,16,4113,92052
반월,2119,4439,2983,16451,353,2609,35548,35285,7872,559,1274,109492
시화,2979,1250,3236,13924,367,6660,62149,23674,7151,1104,2019,124513
시화MTV,0,0,0,485,36,1671,4141,7205,0,0,442,13980
파주탄현,2,3,2,57,0,1,166,27,22,0,1,281
북평,35,0,12,1,2,0,287,9,0,1,403,750
오송생명과학,81,0,0,3841,0,0,0,1043,0,0,120,5085
석문,0,0,0,381,46,110,306,41,560,0,2,1446
아산,386,4,271,4402,305,3150,2371,571,2506,0,961,14927
장항생태,264,0,0,143,0,29,15,0,10,0,0,461
국가식품클러스터,660,0,92,3,0,0,0,0,0,0,192,947
국가식품클러스터(외),X,X,X,X,X,X,X,X,X,X,X,X
군산,16,8,31,468,49,225,925,172,2382,37,153,4466
군산2,230,11,259,736,122,869,1533,46,710,12,203,4731
익산,183,359,2,861,66,0,89,1057,336,209,45,3207
광양,0,23,5,528,1143,8667,2876,355,128,5,637,14367
대불,94,54,94,366,289,115,985,71,2576,10,54,4708
대불(외국인),5,0,0,0,0,0,115,0,787,0,1,908
여수,23,0,27,21722,419,210,1196,170,0,265,992,25024
구미,624,2803,689,5249,4058,863,22088,41007,1368,154,631,79534
구미(외),0,1,0,501,809,0,447,2000,237,0,0,3995
포항,0,0,0,477,644,9268,219,437,586,19,469,12119
포항블루밸리,X,X,X,X,X,X,X,X,X,X,X,X
밀양나노,X,X,X,X,X,X,X,X,X,X,X,X
안정,0,0,0,0,0,0,113,0,877,0,1,991
진해,X,X,X,X,X,X,X,X,X,X,X,X
창원,789,39,267,517,258,9471,61962,27195,15570,194,1525,117787
계,14431,19644,17735,116668,10292,55001,270317,210192,123240,7551,113984,959055

In [12]:
# 'x' 값을 가지는 행 삭제하기
tmp = tmp.replace('X', np.nan).dropna()
tmp

,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조,계
산업단지,,,,,,,,,,,,
서울,814.0,7754.0,3442.0,5880.0,187.0,109.0,7032.0,25509.0,855.0,1623.0,92288.0,145493.0
녹산,995.0,1772.0,465.0,1384.0,207.0,2044.0,13078.0,6047.0,1891.0,164.0,616.0,28663.0
대구,0.0,0.0,0.0,23.0,19.0,0.0,1397.0,732.0,2001.0,0.0,0.0,4172.0
남동,3454.0,355.0,4022.0,14799.0,381.0,3393.0,37933.0,12367.0,4891.0,2672.0,1131.0,85398.0
부평,374.0,468.0,540.0,806.0,5.0,51.0,2372.0,4873.0,302.0,193.0,623.0,10607.0
주안,42.0,190.0,256.0,1317.0,41.0,452.0,2522.0,5301.0,1515.0,265.0,364.0,12265.0
광주첨단,0.0,34.0,0.0,309.0,23.0,8.0,3300.0,11890.0,539.0,0.0,3387.0,19490.0
빛그린,0.0,0.0,29.0,115.0,0.0,0.0,99.0,85.0,655.0,0.0,98.0,1081.0
온산,24.0,8.0,959.0,5393.0,116.0,4052.0,952.0,229.0,1900.0,49.0,1000.0,14682.0
울산ㆍ미포,213.0,69.0,52.0,15529.0,338.0,973.0,4101.0,2777.0,63871.0,16.0,4113.0,92052.0
반월,2119.0,4439.0,2983.0,16451.0,353.0,2609.0,35548.0,35285.0,7872.0,559.0,1274.0,109492.0
시화,2979.0,1250.0,3236.0,13924.0,367.0,6660.0,62149.0,23674.0,7151.0,1104.0,2019.0,124513.0
시화MTV,0.0,0.0,0.0,485.0,36.0,1671.0,4141.0,7205.0,0.0,0.0,442.0,13980.0
파주탄현,2.0,3.0,2.0,57.0,0.0,1.0,166.0,27.0,22.0,0.0,1.0,281.0
북평,35.0,0.0,12.0,1.0,2.0,0.0,287.0,9.0,0.0,1.0,403.0,750.0
오송생명과학,81.0,0.0,0.0,3841.0,0.0,0.0,0.0,1043.0,0.0,0.0,120.0,5085.0
석문,0.0,0.0,0.0,381.0,46.0,110.0,306.0,41.0,560.0,0.0,2.0,1446.0
아산,386.0,4.0,271.0,4402.0,305.0,3150.0,2371.0,571.0,2506.0,0.0,961.0,14927.0
장항생태,264.0,0.0,0.0,143.0,0.0,29.0,15.0,0.0,10.0,0.0,0.0,461.0
국가식품클러스터,660.0,0.0,92.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,192.0,947.0
군산,16.0,8.0,31.0,468.0,49.0,225.0,925.0,172.0,2382.0,37.0,153.0,4466.0
군산2,230.0,11.0,259.0,736.0,122.0,869.0,1533.0,46.0,710.0,12.0,203.0,4731.0
익산,183.0,359.0,2.0,861.0,66.0,0.0,89.0,1057.0,336.0,209.0,45.0,3207.0
광양,0.0,23.0,5.0,528.0,1143.0,8667.0,2876.0,355.0,128.0,5.0,637.0,14367.0
대불,94.0,54.0,94.0,366.0,289.0,115.0,985.0,71.0,2576.0,10.0,54.0,4708.0
대불(외국인),5.0,0.0,0.0,0.0,0.0,0.0,115.0,0.0,787.0,0.0,1.0,908.0
여수,23.0,0.0,27.0,21722.0,419.0,210.0,1196.0,170.0,0.0,265.0,992.0,25024.0
구미,624.0,2803.0,689.0,5249.0,4058.0,863.0,22088.0,41007.0,1368.0,154.0,631.0,79534.0
구미(외),0.0,1.0,0.0,501.0,809.0,0.0,447.0,2000.0,237.0,0.0,0.0,3995.0
포항,0.0,0.0,0.0,477.0,644.0,9268.0,219.0,437.0,586.0,19.0,469.0,12119.0
안정,0.0,0.0,0.0,0.0,0.0,0.0,113.0,0.0,877.0,0.0,1.0,991.0
창원,789.0,39.0,267.0,517.0,258.0,9471.0,61962.0,27195.0,15570.0,194.0,1525.0,117787.0
계,14431.0,19644.0,17735.0,116668.0,10292.0,55001.0,270317.0,210192.0,123240.0,7551.0,113984.0,959055.0

In [13]:
# 계 칼럼 삭제하기
tmp_without_total = tmp.drop(["계"], axis=1)
tmp_without_total

,음식료,섬유의복,목재종이,석유화학,비금속,철강,기계,전기전자,운송장비,기타,비제조
산업단지,,,,,,,,,,,
서울,814.0,7754.0,3442.0,5880.0,187.0,109.0,7032.0,25509.0,855.0,1623.0,92288.0
녹산,995.0,1772.0,465.0,1384.0,207.0,2044.0,13078.0,6047.0,1891.0,164.0,616.0
대구,0.0,0.0,0.0,23.0,19.0,0.0,1397.0,732.0,2001.0,0.0,0.0
남동,3454.0,355.0,4022.0,14799.0,381.0,3393.0,37933.0,12367.0,4891.0,2672.0,1131.0
부평,374.0,468.0,540.0,806.0,5.0,51.0,2372.0,4873.0,302.0,193.0,623.0
주안,42.0,190.0,256.0,1317.0,41.0,452.0,2522.0,5301.0,1515.0,265.0,364.0
광주첨단,0.0,34.0,0.0,309.0,23.0,8.0,3300.0,11890.0,539.0,0.0,3387.0
빛그린,0.0,0.0,29.0,115.0,0.0,0.0,99.0,85.0,655.0,0.0,98.0
온산,24.0,8.0,959.0,5393.0,116.0,4052.0,952.0,229.0,1900.0,49.0,1000.0
울산ㆍ미포,213.0,69.0,52.0,15529.0,338.0,973.0,4101.0,2777.0,63871.0,16.0,4113.0
반월,2119.0,4439.0,2983.0,16451.0,353.0,2609.0,35548.0,35285.0,7872.0,559.0,1274.0
시화,2979.0,1250.0,3236.0,13924.0,367.0,6660.0,62149.0,23674.0,7151.0,1104.0,2019.0
시화MTV,0.0,0.0,0.0,485.0,36.0,1671.0,4141.0,7205.0,0.0,0.0,442.0
파주탄현,2.0,3.0,2.0,57.0,0.0,1.0,166.0,27.0,22.0,0.0,1.0
북평,35.0,0.0,12.0,1.0,2.0,0.0,287.0,9.0,0.0,1.0,403.0
오송생명과학,81.0,0.0,0.0,3841.0,0.0,0.0,0.0,1043.0,0.0,0.0,120.0
석문,0.0,0.0,0.0,381.0,46.0,110.0,306.0,41.0,560.0,0.0,2.0
아산,386.0,4.0,271.0,4402.0,305.0,3150.0,2371.0,571.0,2506.0,0.0,961.0
장항생태,264.0,0.0,0.0,143.0,0.0,29.0,15.0,0.0,10.0,0.0,0.0
국가식품클러스터,660.0,0.0,92.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,192.0
군산,16.0,8.0,31.0,468.0,49.0,225.0,925.0,172.0,2382.0,37.0,153.0
군산2,230.0,11.0,259.0,736.0,122.0,869.0,1533.0,46.0,710.0,12.0,203.0
익산,183.0,359.0,2.0,861.0,66.0,0.0,89.0,1057.0,336.0,209.0,45.0
광양,0.0,23.0,5.0,528.0,1143.0,8667.0,2876.0,355.0,128.0,5.0,637.0
대불,94.0,54.0,94.0,366.0,289.0,115.0,985.0,71.0,2576.0,10.0,54.0
대불(외국인),5.0,0.0,0.0,0.0,0.0,0.0,115.0,0.0,787.0,0.0,1.0
여수,23.0,0.0,27.0,21722.0,419.0,210.0,1196.0,170.0,0.0,265.0,992.0
구미,624.0,2803.0,689.0,5249.0,4058.0,863.0,22088.0,41007.0,1368.0,154.0,631.0
구미(외),0.0,1.0,0.0,501.0,809.0,0.0,447.0,2000.0,237.0,0.0,0.0
포항,0.0,0.0,0.0,477.0,644.0,9268.0,219.0,437.0,586.0,19.0,469.0
안정,0.0,0.0,0.0,0.0,0.0,0.0,113.0,0.0,877.0,0.0,1.0
창원,789.0,39.0,267.0,517.0,258.0,9471.0,61962.0,27195.0,15570.0,194.0,1525.0
계,14431.0,19644.0,17735.0,116668.0,10292.0,55001.0,270317.0,210192.0,123240.0,7551.0,113984.0

In [14]:
# 각 산업단지 별 제일 고용인구가 많은 업종
most = tmp_without_total.idxmax(axis=1)
most

산업단지
서울           비제조
녹산            기계
대구          운송장비
남동            기계
부평          전기전자
주안          전기전자
광주첨단        전기전자
빛그린         운송장비
온산          석유화학
울산ㆍ미포       운송장비
반월            기계
시화            기계
시화MTV       전기전자
파주탄현          기계
북평           비제조
오송생명과학      석유화학
석문          운송장비
아산          석유화학
장항생태         음식료
국가식품클러스터     음식료
군산          운송장비
군산2           기계
익산          전기전자
광양            철강
대불          운송장비
대불(외국인)     운송장비
여수          석유화학
구미          전기전자
구미(외)       전기전자
포항            철강
안정          운송장비
창원            기계
계             기계
dtype: object

In [16]:
# 각 산업단지 별 제일 고용인구가 많은 업종의 고용인구 수
most = tmp_without_total.max(axis=1)
most

산업단지
서울           92288.0
녹산           13078.0
대구            2001.0
남동           37933.0
부평            4873.0
주안            5301.0
광주첨단         11890.0
빛그린            655.0
온산            5393.0
울산ㆍ미포        63871.0
반월           35548.0
시화           62149.0
시화MTV         7205.0
파주탄현           166.0
북평             403.0
오송생명과학        3841.0
석문             560.0
아산            4402.0
장항생태           264.0
국가식품클러스터       660.0
군산            2382.0
군산2           1533.0
익산            1057.0
광양            8667.0
대불            2576.0
대불(외국인)        787.0
여수           21722.0
구미           41007.0
구미(외)         2000.0
포항            9268.0
안정             877.0
창원           61962.0
계           270317.0
dtype: float64

In [17]:
# 각 산업단지 별 제일 고용인구가 많은 종목의 차지비율
percentage = most / tmp_without_total.sum(axis=1) * 100
percentage

산업단지
서울          63.431230
녹산          45.626766
대구          47.962608
남동          44.419073
부평          45.941359
주안          43.220546
광주첨단        61.005644
빛그린         60.592044
온산          36.732053
울산ㆍ미포       69.385782
반월          32.466299
시화          49.913664
시화MTV       51.537911
파주탄현        59.074733
북평          53.733333
오송생명과학      75.535890
석문          38.727524
아산          29.490186
장항생태        57.266811
국가식품클러스터    69.693770
군산          53.336319
군산2         32.403297
익산          32.959152
광양          60.325747
대불          54.715378
대불(외국인)     86.674009
여수          86.804668
구미          51.559082
구미(외)       50.062578
포항          76.474957
안정          88.496468
창원          52.605126
계           28.185766
dtype: float64